/**
 * css.js — CSS builder for generated Undercity apps.
 *
 * Produces the shared flow.css written to every generated project.
 * Plugins may contribute additional CSS via the registry.
 *
 * Design system: Solarized Dark + Bootstrap 5.3 dark mode.
 * All colours use CSS custom properties for easy theming.
 */

export function buildFlowCSS(proj, extras = []) {
  const base = `/* flow.css — Generated by Undercity IDE for: ${proj.name} */

/* ── Solarized Dark palette ─────────────────────────────────────────────── */
:root {
  --sol-base03:  #002b36;
  --sol-base02:  #073642;
  --sol-base01:  #586e75;
  --sol-base0:   #839496;
  --sol-base1:   #93a1a1;
  --sol-yellow:  #b58900;
  --sol-orange:  #cb4b16;
  --sol-red:     #dc322f;
  --sol-magenta: #d33682;
  --sol-violet:  #6c71c4;
  --sol-blue:    #268bd2;
  --sol-cyan:    #2aa198;
  --sol-green:   #859900;

  /* Semantic aliases */
  --pw-bg:       var(--sol-base03);
  --pw-surface:  var(--sol-base02);
  --pw-border:   rgba(38,139,210,.22);
  --pw-text:     var(--sol-base0);
  --pw-text-em:  var(--sol-base1);
  --pw-accent:   var(--sol-cyan);
}

/* ── Base ────────────────────────────────────────────────────────────────── */
body.pw-page {
  background: var(--pw-bg);
  color: var(--pw-text);
}

/* ── Navigation bar ─────────────────────────────────────────────────────── */
.navbar.navbar-dark {
  background: var(--pw-surface) !important;
}
.navbar .navbar-brand {
  font-size: .9rem;
  letter-spacing: -.01em;
}

/* ── Bootstrap card (dark theme) ────────────────────────────────────────── */
body.pw-page .card {
  --bs-card-bg: var(--pw-surface);
  --bs-card-border-color: var(--pw-border);
  --bs-card-color: var(--pw-text);
  border-radius: 14px;
  box-shadow: 0 6px 40px rgba(0,0,0,.45);
}
body.pw-page .card-body { padding: 2rem 2.25rem; }
@media (max-width: 576px) {
  body.pw-page .card { border-radius: 10px; }
  body.pw-page .card-body { padding: 1.5rem 1.25rem; }
}
/* render.* inner cards (multiple per page) — flush with bg, no shadow */
#pw-content > .card {
  --bs-card-bg: var(--pw-bg);
  box-shadow: none;
  border-radius: 10px;
}
#pw-content > .card .card-body { padding: 1.25rem 1.5rem; }
#pw-content > .card .form-label { color: var(--sol-base1); }

/* ── Heading ────────────────────────────────────────────────────────────── */
.pw-heading {
  color: var(--sol-cyan);
  font-weight: 700;
  letter-spacing: -.025em;
  margin-bottom: 3rem;
}

/* ── Form inputs (override Bootstrap dark-mode defaults) ────────────────── */
.pw-input,
.pw-input.form-control,
.pw-input.form-select {
  background: var(--sol-base03) !important;
  border-color: rgba(38,139,210,.28) !important;
  color: var(--sol-base1) !important;
}
.pw-input:focus,
.pw-input.form-control:focus,
.pw-input.form-select:focus {
  border-color: var(--sol-blue) !important;
  box-shadow: 0 0 0 3px rgba(38,139,210,.22) !important;
  outline: none;
}
.pw-input::placeholder { color: var(--sol-base01) !important; opacity: 1; }

/* Bootstrap validation states — keep colours legible on dark bg */
.pw-input.is-invalid,
.pw-input.form-control.is-invalid {
  border-color: var(--sol-red) !important;
  background-image: none !important;
}
.pw-input.is-invalid:focus,
.pw-input.form-control.is-invalid:focus {
  box-shadow: 0 0 0 3px rgba(220,50,47,.22) !important;
}
.invalid-feedback { color: var(--sol-red); font-size: .8125rem; }
.valid-feedback   { color: var(--sol-green); font-size: .8125rem; }

/* ── Modal ──────────────────────────────────────────────────────────────── */
.pw-modal-content {
  background: var(--pw-surface);
  border: 1px solid rgba(38,139,210,.3);
}

/* ── Review table ───────────────────────────────────────────────────────── */
.table-dark.table-borderless { --bs-table-bg: transparent; }
.table-dark.table-borderless th,
.table-dark.table-borderless td { border: none; }

/* ── Footer ─────────────────────────────────────────────────────────────── */
footer { background: var(--pw-surface); }

/* ── Scrollbar ──────────────────────────────────────────────────────────── */
::-webkit-scrollbar { width: 5px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--sol-base01); border-radius: 3px; }
`;

  return [base, ...extras].join('\n');
}
