/**
 * runtime.js — Generates the runtime.js bundle embedded in every Undercity app.
 *
 * The runtime provides:
 *   Inventory  — session-persisted key/value store
 *   Bus        — typed event bus
 *   Navigator  — page-routing helpers (entry node resolves to index.html)
 *   Actions    — built-in action library (DOM, Forms, HTTP, UI)
 *   route()    — diamond routing helper
 *   runPayload() — executes a node's action payload array
 *
 * Namespace aliases in runPayload (case-insensitive, common shorthands):
 *   inventory / Inventory → Inventory
 *   navigator / Navigator → Navigator
 *   actions / Actions / dom / form / ui → Actions
 *
 * The "into" param: any action that returns a value can store it in Inventory
 * by setting { "into": "fieldName" } in the params object.
 *
 * Plugins contribute extension blocks appended after the core (registerNamespace).
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const MD_RENDERER_CODE = readFileSync(join(__dir, 'md-renderer-src.js'), 'utf8');

/**
 * @param {object}   proj       - Project descriptor
 * @param {object[]} nodes      - Graph nodes
 * @param {object[]} edges      - Graph edges
 * @param {string[]} [extensions] - Extra JS blocks from plugins
 * @returns {string} - Full runtime.js source
 */
export function buildRuntime(proj, nodes, edges, extensions = []) {
  const inventory = proj.inventory?.schema ?? {};
  const defaults  = Object.fromEntries(
    Object.entries(inventory).map(([k, v]) => [k, v.default ?? null])
  );
  const entryId = nodes.find(n => n.meta?.isEntry)?.id ?? 'index';
  const extCode = extensions.length ? `\n\n${extensions.join('\n\n')}` : '';

  return `/**
 * runtime.js — Generated by Undercity 2 IDE
 * Project : ${proj.name}
 * Generated: ${new Date().toISOString()}
 *
 * Architecture: PUSH — Inventory keys are Signals. Subscribers receive values
 * automatically when inventory changes. No polling, no $$inv magic.
 *
 * Key APIs:
 *   Inventory.set(key, value)          — write + push to all subscribers
 *   Inventory.get(key)                 — synchronous snapshot read
 *   Inventory.signal(key)              — get/create a live Signal for a key
 *   Inventory.subscribe(key, fn)       — fn(value) fires now + on every change
 *   Inventory.signals                  — Map<key, Signal> of all active signals
 */

// ── Signal ─────────────────────────────────────────────────────────────────────
// Minimal reactive value cell. subscribe(fn) fires fn immediately with the
// current value, then on every change. Returns { dispose() } for cleanup.
class _Signal {
  #v; #subs = new Set();
  constructor(init) { this.#v = init; }
  get value()  { return this.#v; }
  set value(v) {
    if (Object.is(v, this.#v)) return;
    this.#v = v;
    for (const fn of [...this.#subs]) fn(v);
  }
  subscribe(fn, autorun = true) {
    this.#subs.add(fn);
    if (autorun) fn(this.#v);
    return { dispose: () => this.#subs.delete(fn) };
  }
  peek() { return this.#v; }
}

// ── Inventory ─────────────────────────────────────────────────────────────────
// Each key has its own Signal. set() writes synchronously AND pushes to all
// subscribers of that key. No bus events needed — subscribe directly.
export const Inventory = (() => {
  const DEFAULTS = ${JSON.stringify(defaults, null, 2)};
  const KEY = 'undercity2_inv_${proj.id}';
  let _data = { ...DEFAULTS };
  const _sigs = new Map();           // Map<key, _Signal>

  function _sig(key) {
    if (!_sigs.has(key)) _sigs.set(key, new _Signal(_data[key] ?? null));
    return _sigs.get(key);
  }
  function _load() {
    try { _data = { ...DEFAULTS, ...JSON.parse(sessionStorage.getItem(KEY) ?? '{}') }; } catch {}
  }
  function _save() { sessionStorage.setItem(KEY, JSON.stringify(_data)); }
  _load();

  return {
    // ── Core read/write ──────────────────────────────────────────────────────
    get(key)        { return key ? _data[key] : { ..._data }; },
    set(key, value) { _data[key] = value; _save(); _sig(key).value = value; },
    merge(obj)      { Object.assign(_data, obj); _save(); for (const [k, v] of Object.entries(obj)) _sig(k).value = v; },
    delete(key)     { delete _data[key]; _save(); _sig(key).value = undefined; },
    clear()         { _data = { ...DEFAULTS }; _save(); for (const [, s] of _sigs) s.value = null; },

    // ── Push API (signals) ───────────────────────────────────────────────────
    /** Get (or create) the live Signal for a key. */
    signal(key) { return _sig(key); },

    /**
     * Subscribe to a specific inventory key.
     * fn(value) fires immediately with the current value, then on every change.
     * Returns { dispose() } — call dispose() to stop receiving updates.
     *
     * Example:
     *   const sub = Inventory.subscribe('userEmail', email => console.log(email));
     *   // later:
     *   sub.dispose();
     */
    subscribe(key, fn) { return _sig(key).subscribe(fn); },

    /** Map of all currently active Signals. */
    get signals() { return new Map(_sigs); },

    // ── Utilities ────────────────────────────────────────────────────────────
    check(expr)  { try { const inventory = _data; return !!eval(expr); } catch { return false; } },
    dump()       { return JSON.parse(JSON.stringify(_data)); },
  };
})();

// Expose to the browser debug console so you can type Inventory.dump() in DevTools.
globalThis.Inventory = Inventory;

// ── Event Bus ─────────────────────────────────────────────────────────────────
// Bus remains for non-inventory events (navigation, custom app events, etc.)
// Inventory changes are handled by Inventory.subscribe() — not Bus events.
export const Bus = (() => {
  const handlers = new Map();
  return {
    on(event, fn)     { const s = handlers.get(event) ?? new Set(); s.add(fn); handlers.set(event, s); return { dispose: () => s.delete(fn) }; },
    off(event, fn)    { handlers.get(event)?.delete(fn); },
    emit(event, data) { for (const fn of handlers.get(event) ?? []) fn(data); },
    once(event, fn)   { const h = Bus.on(event, d => { fn(d); h.dispose(); }); },
  };
})();

// ── Navigator ─────────────────────────────────────────────────────────────────
// The entry node is served as index.html for static-hosting friendliness.
// _pageName() maps the entry node id → 'index' everywhere else uses node id.
const _BASE    = import.meta.url.replace(/\\/js\\/runtime\\.js$/, '');
const _ENTRY   = '${entryId}';
function _pageName(room) { return room === _ENTRY ? 'index' : room; }

export const Navigator = {
  goto(room)  { window.location.href = _BASE + '/' + _pageName(room) + '.html'; },
  back()         { window.history.back(); },
  // reset: clear inventory, return to entry (keeps existing data when called with keepData=true)
  reset(keepData = false) { if (!keepData) Inventory.clear(); Navigator.goto(_ENTRY); },
  reload()       { window.location.reload(); },
};

// ── Breadcrumb / Room History ──────────────────────────────────────────────────
// Tracks which rooms (rooms) the user has visited, in order.
// Stored in sessionStorage so it persists across same-tab navigation.
export const History = (() => {
  const KEY = 'undercity_hist_${proj.id}';
  function _load() { try { return JSON.parse(sessionStorage.getItem(KEY) ?? '[]'); } catch { return []; } }
  function _save(h) { sessionStorage.setItem(KEY, JSON.stringify(h)); }
  return {
    push(roomId) { const h = _load(); if (h[h.length-1] !== roomId) { h.push(roomId); _save(h); } },
    pop()           { const h = _load(); const s = h.pop(); _save(h); return s; },
    peek()          { const h = _load(); return h[h.length-1]; },
    all()           { return _load(); },
    clear()         { _save([]); },
  };
})();

// ── User ────────────────────────────────────────────────────────────────────
// The User is the player navigating the dungeon (the person filling the form).
// In MUD terms: the user inhabits a room (location) and carries an inventory.
//
//   User.location  — current room ID (room the user is standing in)
//   User.carry()   — pick up a named item (rich object) into inventory
//   User.drop()    — discard a carried item
//   User.has()     — check whether an item is currently carried
//   User.inspect() — examine a carried item
//
// User.* also proxies all Inventory methods for backwards compatibility so
// that "user.set", "user.get" etc. continue to work in payloads.
export const User = (() => {
  return {
    /** Current room ID — read from the page's data-node attribute on <body>. */
    get location() {
      return document.body?.dataset?.node ?? History.peek() ?? null;
    },

    /**
     * Pick up a named item and carry it in inventory.
     *   User.carry('authToken', { token: 'abc', expires: '2026-12-31' })
     *   User.carry('medicalForm', { type: 'form', status: 'incomplete', data: {} })
     */
    carry(itemId, itemData = {}) {
      Inventory.set(itemId, {
        _isItem: true,
        _carriedAt: new Date().toISOString(),
        ...itemData,
      });
    },

    /** Drop (remove) a carried item from inventory. */
    drop(itemId) { Inventory.delete(itemId); },

    /** Returns true if the user is carrying a non-empty value for itemId. */
    has(itemId) {
      const v = Inventory.get(itemId);
      return v !== null && v !== undefined && v !== '' && v !== false;
    },

    /** Examine the full value of a carried item. */
    inspect(itemId) { return Inventory.get(itemId); },

    // ── Inventory delegates ────────────────────────────────────────────────────
    get(key)        { return Inventory.get(key); },
    set(key, value) { Inventory.set(key, value); },
    merge(obj)      { Inventory.merge(obj); },
    delete(key)     { Inventory.delete(key); },
    clear()         { Inventory.clear(); },
    check(expr)     { return Inventory.check(expr); },
    dump()          { return Inventory.dump(); },
  };
})();

// ── Binding registry (live-sync cleanup) ──────────────────────────────────────
// Each call to Actions.bindField() registers cleanup functions here.
// All cleanups run on pagehide to prevent memory leaks during navigation.
const _pwBindings = [];
function _pwRegisterBinding(fn) { _pwBindings.push(fn); }
window.addEventListener('pagehide', () => { _pwBindings.forEach(fn => fn()); _pwBindings.length = 0; });

// ── Actions ───────────────────────────────────────────────────────────────────
export const Actions = {
  // DOM — show/hide/toggle
  show(sel)                { document.querySelectorAll(sel).forEach(el => el.classList.remove('d-none')); },
  hide(sel)                { document.querySelectorAll(sel).forEach(el => el.classList.add('d-none')); },
  toggle(sel)              { document.querySelectorAll(sel).forEach(el => el.classList.toggle('d-none')); },
  setText(sel, text)       { document.querySelectorAll(sel).forEach(el => el.textContent = text); },
  setHtml(sel, html)       { document.querySelectorAll(sel).forEach(el => el.innerHTML = html); },
  setAttr(sel, attr, val)  { document.querySelectorAll(sel).forEach(el => el.setAttribute(attr, val)); },
  addClass(sel, cls)       { document.querySelectorAll(sel).forEach(el => el.classList.add(cls)); },
  removeClass(sel, cls)    { document.querySelectorAll(sel).forEach(el => el.classList.remove(cls)); },
  toggleClass(sel, cls)    { document.querySelectorAll(sel).forEach(el => el.classList.toggle(cls)); },
  setStyle(sel, prop, val) { document.querySelectorAll(sel).forEach(el => el.style[prop] = val); },
  scroll(sel, block='start') { document.querySelector(sel)?.scrollIntoView({ behavior:'smooth', block }); },
  focus(sel)               { document.querySelector(sel)?.focus(); },

  // Forms — Bootstrap is-invalid / invalid-feedback pattern
  getField(name)  { return document.querySelector(\`[name="\${name}"]\`)?.value?.trim() ?? ''; },
  setField(name, invKey) { const el = document.querySelector(\`[name="\${name}"]\`); if (el) el.value = String(Inventory.get(invKey) ?? ''); },
  clearField(name)    { Actions.setField(name, ''); },
  setError(name, msg) {
    const input = document.querySelector(\`[name="\${name}"]\`);
    const errEl = document.querySelector(\`[data-error="\${name}"]\`);
    input?.classList.add('is-invalid');
    input?.setAttribute('aria-invalid', 'true');
    if (errEl) errEl.textContent = msg;
  },
  clearErrors() {
    document.querySelectorAll('[data-error]').forEach(el => { el.textContent = ''; });
    document.querySelectorAll('.is-invalid').forEach(el => { el.classList.remove('is-invalid'); el.removeAttribute('aria-invalid'); });
  },
  serializeForm(sel) {
    const form = document.querySelector(sel);
    return form ? Object.fromEntries(new FormData(form).entries()) : {};
  },
  /** Run HTML5 + custom validation. Marks is-valid/is-invalid on each field, returns true if all pass. */
  validate(sel = 'form') {
    const form = document.querySelector(sel);
    if (!form) return true;
    let valid = true;
    form.querySelectorAll('[required],[minlength],[maxlength],[pattern],[min],[max]').forEach(el => {
      if (!el.checkValidity()) {
        el.classList.add('is-invalid');
        el.classList.remove('is-valid');
        valid = false;
      } else {
        el.classList.remove('is-invalid');
        el.classList.add('is-valid');
      }
    });
    if (!valid) {
      const first = form.querySelector('.is-invalid');
      first?.focus();
      first?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
    return valid;
  },
  getSelect(name)  { const el = document.querySelector(\`[name="\${name}"]\`); return el?.value ?? ''; },
  getCheck(name)   { const el = document.querySelector(\`[name="\${name}"]\`); return el?.checked ?? false; },
  setCheck(name, v){ const el = document.querySelector(\`[name="\${name}"]\`); if (el) el.checked = !!v; },
  getRange(name)   { const el = document.querySelector(\`[name="\${name}"]\`); return el ? Number(el.value) : 0; },
  bindField(fieldName, invKey) {
    const el = document.querySelector(\`[name="\${fieldName}"]\`);
    if (!el) return;
    const disposer = Inventory.subscribe(invKey, v => {
      if (!el.ownerDocument.contains(el)) return;
      const nv = String(v ?? '');
      if (el.value !== nv) el.value = nv;
    });
    const onInput = () => Inventory.set(invKey, el.value);
    el.addEventListener('input', onInput);
    _pwRegisterBinding(() => { el.removeEventListener('input', onInput); disposer.dispose(); });
  },

  // HTTP
  async fetch(url, opts = {}) { const r = await fetch(url, opts); return r.ok ? r.json() : Promise.reject(await r.text()); },
  async get(url)               { return Actions.fetch(url); },
  async post(url, body)        { return Actions.fetch(url, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(body) }); },

  // Submit: POST inventory (or a subset) to a URL.
  async submit(url, fields = null) {
    const data = fields ? Object.fromEntries(fields.map(k => [k, Inventory.get(k)])) : Inventory.dump();
    const res  = await Actions.post(url, data);
    Inventory.set('lastSubmitResponse', res);
    return res;
  },

  // UI feedback
  toast(msg, type = 'info') {
    const el = document.createElement('div');
    el.className = \`alert alert-\${type} position-fixed bottom-0 end-0 m-3 shadow-sm fade show\`;
    el.style.cssText = 'z-index:9999;min-width:220px;max-width:360px';
    el.setAttribute('role', 'alert');
    el.textContent = msg;
    document.body.appendChild(el);
    setTimeout(() => el.remove(), 3500);
  },
  loading(show = true) { document.getElementById('pw-loading')?.classList.toggle('d-none', !show); },

  // Input prompts
  askInput(label = 'Input', placeholder = '', type = 'text') {
    return new Promise(resolve => {
      const modal = document.getElementById('pw-input-modal');
      if (!modal) { resolve(null); return; }
      modal.querySelector('#pw-input-label').textContent = label;
      const inp = modal.querySelector('#pw-input-field');
      inp.type = type; inp.placeholder = placeholder; inp.value = '';
      const bsModal = bootstrap.Modal.getOrCreateInstance(modal);
      const handler = () => { const val = inp.value; resolve(val); bsModal.hide(); };
      modal.querySelector('#pw-input-confirm').onclick = handler;
      bsModal.show();
    });
  },
  askText(label = 'Input', placeholder = '', multiline = false) {
    return new Promise(resolve => {
      const modal = document.getElementById('pw-input-modal');
      if (!modal) { resolve(null); return; }
      modal.querySelector('#pw-input-label').textContent = label;
      const body = modal.querySelector('.modal-body');

      // Swap between input and textarea based on multiline flag
      let field = modal.querySelector('#pw-input-field');
      let ta = modal.querySelector('#pw-input-textarea');
      if (multiline) {
        if (!ta) {
          ta = document.createElement('textarea');
          ta.id = 'pw-input-textarea';
          ta.className = 'form-control pw-input';
          ta.rows = 5;
          body.appendChild(ta);
        }
        field.style.display = 'none';
        ta.style.display = '';
        ta.placeholder = placeholder; ta.value = '';
        field = ta;
      } else {
        if (ta) ta.style.display = 'none';
        field.style.display = '';
        field.type = 'text'; field.placeholder = placeholder; field.value = '';
      }

      const bsModal = bootstrap.Modal.getOrCreateInstance(modal);
      const handler = () => { const val = field.value; resolve(val); bsModal.hide(); };
      modal.querySelector('#pw-input-confirm').onclick = handler;
      bsModal.show();
    });
  },
  askVideoUpload({ accept = 'video/*', into } = {}) {
    return new Promise(resolve => {
      const inp = document.createElement('input');
      inp.type = 'file'; inp.accept = accept; inp.style.display = 'none';
      document.body.appendChild(inp);
      inp.onchange = () => {
        const file = inp.files[0] ?? null;
        if (file && into) Inventory.set(into, { name: file.name, size: file.size, type: file.type, url: URL.createObjectURL(file) });
        resolve(file); inp.remove();
      };
      inp.click();
    });
  },

  delay(ms)    { return new Promise(r => setTimeout(r, ms)); },
  log(...args) { console.log('[Undercity]', ...args); },
};

${MD_RENDERER_CODE}

// ── Display ───────────────────────────────────────────────────────────────────
// Writes content into EXISTING elements already on the page.
export const Display = {
  /** Set plain text (safe, no HTML interpretation). */
  text(selector, text) {
    document.querySelectorAll(selector).forEach(el => { el.textContent = String(text ?? ''); });
  },
  /** Render Markdown into a selector (wraps in div.af-md). */
  markdown(selector, content) {
    const html = _renderMd(String(content ?? ''));
    document.querySelectorAll(selector).forEach(el => {
      el.innerHTML = \`<div class="af-md">\${html}</div>\`;
    });
  },
  /** Inject sanitized HTML (strips scripts/event-handlers). */
  safeHtml(selector, html) {
    const safe = _sanitizeHtml(String(html ?? ''));
    document.querySelectorAll(selector).forEach(el => { el.innerHTML = safe; });
  },
  /** Inject raw trusted HTML directly (no sanitization). */
  rawHtml(selector, html) {
    document.querySelectorAll(selector).forEach(el => { el.innerHTML = String(html ?? ''); });
  },
  /** Empty the contents of a selector. */
  clear(selector) {
    document.querySelectorAll(selector).forEach(el => { el.innerHTML = ''; });
  },
  /** Print an inventory key's value as text into a selector. */
  value(selector, key) {
    const v = Inventory.get(key);
    Display.text(selector, v ?? '');
  },
};

// ── Shared page container resolver ────────────────────────────────────────────
// Resolution order:
//   1. #pw-content  — blank-template rooms (render.* target)
//   2. #pw-form     — form-template rooms
//   3. main#pw-main .container-* — default/null-template rooms
//   4. document.body — absolute last resort
function _pwContainer() {
  return document.getElementById('pw-content')
      ?? document.getElementById('pw-form')
      ?? document.querySelector('main#pw-main [class*="container"]')
      ?? document.body;
}
/** Insert child into parent before #pw-nav-card so nav stays pinned at bottom. */
function _pwInsert(parent, child) {
  const nav = parent.querySelector?.(':scope > #pw-nav-card') ?? null;
  parent.insertBefore(child, nav);
}
/** Return the .card-body of the last content card, creating a new card if none exists. */
function _pwCardBody() {
  const root  = _pwContainer();
  const cards = [...root.querySelectorAll(':scope > .card:not(#pw-nav-card)')];
  if (cards.length) return cards[cards.length - 1].querySelector(':scope > .card-body');
  const card = document.createElement('div');
  card.className = 'card mb-3';
  const body = document.createElement('div');
  body.className = 'card-body';
  card.appendChild(body);
  _pwInsert(root, card);
  return body;
}

// ── Render (Page Builder) ─────────────────────────────────────────────────────
// Appends Bootstrap-styled components into Bootstrap .card > .card-body sections.
// Use on rooms with template: "blank". Call render.clear in onEnter first.
// render.divider() closes the current card and starts a new one.
export const Render = (() => {
  /** Root container for render.* output. */
  function _root() { return _pwContainer(); }
  /** Create a new Bootstrap card inserted before #pw-nav-card. */
  function _newCard(root) {
    const card = document.createElement('div');
    card.className = 'card mb-3';
    const body = document.createElement('div');
    body.className = 'card-body';
    card.appendChild(body);
    _pwInsert(root, card);
    return card;
  }
  /** Return the .card-body of the last content card (creating one if absent). */
  function _card() { return _pwCardBody(); }
  function _esc(s)     { return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  function _escA(s)    { return String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  function _navFn(id)  { return 'goTo_' + String(id).replace(/[^a-zA-Z0-9]/g,'_'); }

  return {
    /** Clear #pw-content — call first in onEnter to rebuild. */
    clear() { const r=_root(); if(r) r.innerHTML=''; },

    /** Close the current card and start a fresh one. Use to divide the form into sections. */
    divider() { _newCard(_root()); },

    /** Append a heading. */
    title(text, size='h2') {
      const el=document.createElement(size);
      el.className='pw-heading mb-1';
      el.textContent=String(text??'');
      _card().appendChild(el);
    },

    /** Append a muted subtitle. */
    subtitle(text) {
      const p=document.createElement('p');
      p.className='text-muted small mb-4';
      p.textContent=String(text??'');
      _card().appendChild(p);
    },

    /** Append a paragraph. style: muted|info|success|warning|danger|body */
    paragraph(text, style='muted') {
      const p=document.createElement('p');
      p.className=style==='body'?'mb-3':\`text-\${style} small mb-2\`;
      p.textContent=String(text??'');
      _card().appendChild(p);
    },

    /** Append a Bootstrap form field (label + input + valid/invalid feedback). Supports type='textarea'. */
    field(name='', label='', type='text', placeholder='', autocomplete='', required=false) {
      const id=\`pw-field-\${_escA(name)}\`;
      const req=Boolean(required)||(String(required)==='true');
      const isTA=type==='textarea';
      const div=document.createElement('div');
      div.className='mb-3';
      const inputHtml=isTA
        ? \`<textarea id="\${id}" name="\${_escA(name)}" rows="4"
  class="form-control pw-input"
  placeholder="\${_escA(placeholder)}"
  \${req?'aria-required="true" required':''}
  aria-describedby="\${id}-error \${id}-ok"></textarea>\`
        : \`<input type="\${_escA(type)}" id="\${id}" name="\${_escA(name)}"
  class="form-control pw-input"
  placeholder="\${_escA(placeholder)}"
  \${autocomplete?'autocomplete="'+_escA(autocomplete)+'"':''}\${req?' aria-required="true" required':''}
  aria-describedby="\${id}-error \${id}-ok">\`;
      div.innerHTML=\`<label for="\${id}" class="form-label">\${_esc(label)}</label>
\${inputHtml}
<div id="\${id}-ok" class="valid-feedback">Looks good!</div>
<div id="\${id}-error" class="invalid-feedback" data-error="\${_escA(name)}"></div>\`;
      _card().appendChild(div);
    },

    /** Append a multi-line textarea field. */
    textarea(name='', label='', placeholder='', rows=4, required=false) {
      Render.field(name, label, 'textarea', placeholder, '', required);
    },

    /** Append a Bootstrap <select> dropdown. options: CSV string or array. */
    select(name='', label='', options='', defaultVal='', required=false) {
      const id=\`pw-field-\${_escA(name)}\`;
      const req=Boolean(required)||(String(required)==='true');
      const opts=(Array.isArray(options)?options:String(options).split(','))
        .map(o=>o.trim()).filter(Boolean)
        .map(o=>\`<option value="\${_escA(o)}"\${o===defaultVal?' selected':''}>\${_esc(o)}</option>\`)
        .join('');
      const div=document.createElement('div');
      div.className='mb-3';
      div.innerHTML=\`<label for="\${id}" class="form-label">\${_esc(label)}</label>
<select id="\${id}" name="\${_escA(name)}" class="form-select pw-input"\${req?' required':''} aria-describedby="\${id}-error \${id}-ok">
  <option value="" disabled\${defaultVal?'':' selected'}>Choose…</option>
  \${opts}
</select>
<div id="\${id}-ok" class="valid-feedback">Looks good!</div>
<div id="\${id}-error" class="invalid-feedback" data-error="\${_escA(name)}"></div>\`;
      _card().appendChild(div);
    },

    /** Append a Bootstrap checkbox. */
    checkbox(name='', label='', checked=false, required=false) {
      const id=\`pw-field-\${_escA(name)}\`;
      const req=Boolean(required)||(String(required)==='true');
      const chk=Boolean(checked)||(String(checked)==='true');
      const div=document.createElement('div');
      div.className='mb-3 form-check';
      div.innerHTML=\`<input class="form-check-input pw-input" type="checkbox" id="\${id}" name="\${_escA(name)}"
  \${chk?'checked':''}
  \${req?'required':''}
  aria-describedby="\${id}-error">
<label class="form-check-label" for="\${id}">\${_esc(label)}</label>
<div id="\${id}-error" class="invalid-feedback" data-error="\${_escA(name)}"></div>\`;
      _card().appendChild(div);
    },

    /** Append a Bootstrap alert box (hidden by default if text is empty). */
    alert(id='pw-alert', type='danger', text='') {
      const div=document.createElement('div');
      div.id=id;
      div.className=\`alert alert-\${_escA(type)} py-2\${text?'':' d-none'}\`;
      div.setAttribute('role','alert');
      div.setAttribute('aria-live','polite');
      if(text) div.textContent=String(text);
      _card().appendChild(div);
    },

    /** Append a button that calls goTo_<target>() (runs onExit then navigates). */
    button(label='', target='', variant='primary', full=true) {
      const btn=document.createElement('button');
      btn.type='button';
      btn.className=\`btn btn-\${_escA(variant)} fw-semibold\${(full===true||String(full)==='true')?' w-100 mt-3':' mt-2'}\`;
      btn.textContent=String(label);
      btn.addEventListener('click',()=>{
        const fn=_navFn(target);
        if(typeof window[fn]==='function') window[fn]();
        else if(target) Navigator.goto(target);
      });
      _card().appendChild(btn);
    },

    /** Append a small centred text link navigating to a room. */
    link(text='', target='', prefix='') {
      const p=document.createElement('p');
      p.className='text-center text-muted small mt-3 mb-0';
      const a=document.createElement('a');
      a.href='#';
      a.className='text-info';
      a.textContent=String(text);
      a.addEventListener('click', e => {
        e.preventDefault();
        const fn=_navFn(target);
        if(typeof window[fn]==='function') window[fn]();
        else if(target) Navigator.goto(target);
      });
      if(prefix) p.append(String(prefix)+' ');
      p.appendChild(a);
      _card().appendChild(p);
    },

    /** Append an uppercase section label. */
    section(title) {
      const div=document.createElement('div');
      div.className='text-uppercase fw-semibold text-muted small mt-3 mb-1';
      div.style.letterSpacing='.08em';
      div.textContent=String(title??'');
      _card().appendChild(div);
    },

    /** Append a rendered Markdown block. */
    markdown(content) {
      const html=_renderMd(String(content??''));
      const div=document.createElement('div');
      div.className='af-md mb-3';
      div.innerHTML=html;
      _card().appendChild(div);
    },
  };
})();

// ── Media / File Upload ───────────────────────────────────────────────────────
export const Media = (() => {
  function _ct() { return _pwContainer(); }
  function _fileToObj(file) {
    return { name: file.name, size: file.size, type: file.type, url: URL.createObjectURL(file) };
  }
  function _uploadUI({ label='Select a file', accept='*/*', multiple=false, showPreview=false, previewType=null }) {
    return new Promise(resolve => {
      const wrap = document.createElement('div');
      wrap.className = 'pw-media-wrap';

      const promptEl = document.createElement('label');
      promptEl.className = 'form-label fw-semibold';
      promptEl.textContent = label;

      const inp = document.createElement('input');
      inp.type = 'file';
      inp.accept = accept || '*/*';
      if (multiple) inp.multiple = true;
      inp.className = 'form-control mb-3';

      const previewEl = document.createElement('div');
      previewEl.className = 'pw-media-preview mb-3 d-none';

      const confirmBtn = document.createElement('button');
      confirmBtn.type = 'button';
      confirmBtn.className = 'btn btn-primary w-100 d-none';
      confirmBtn.textContent = 'Continue';

      wrap.append(promptEl, inp, previewEl, confirmBtn);
      _pwCardBody().appendChild(wrap);

      inp.addEventListener('change', () => {
        const file = inp.files[0];
        if (!file) return;
        if (showPreview && previewType) {
          previewEl.innerHTML = '';
          previewEl.classList.remove('d-none');
          const url = URL.createObjectURL(file);
          if (previewType === 'image') {
            const img = document.createElement('img');
            img.src = url; img.className = 'img-fluid rounded'; img.style.maxHeight = '240px';
            previewEl.appendChild(img);
          } else if (previewType === 'video') {
            const vid = document.createElement('video');
            vid.src = url; vid.controls = true; vid.className = 'w-100 rounded'; vid.style.maxHeight = '240px';
            previewEl.appendChild(vid);
          } else if (previewType === 'audio') {
            const aud = document.createElement('audio');
            aud.src = url; aud.controls = true; aud.className = 'w-100';
            previewEl.appendChild(aud);
          }
          confirmBtn.classList.remove('d-none');
        } else {
          wrap.remove();
          resolve(multiple ? Array.from(inp.files).map(_fileToObj) : _fileToObj(file));
        }
      });

      confirmBtn.addEventListener('click', () => {
        const files = Array.from(inp.files);
        if (!files.length) return;
        wrap.remove();
        resolve(multiple ? files.map(_fileToObj) : _fileToObj(files[0]));
      });
    });
  }

  return {
    askVideoUpload(label='Upload a video', accept='video/*', thumbnailPrompt='', extractThumb=true) {
      return _uploadUI({ label, accept, showPreview: !!extractThumb, previewType: 'video' });
    },
    askImageUpload(label='Upload an image', accept='image/*', preview=true) {
      return _uploadUI({ label, accept, showPreview: !!preview, previewType: 'image' });
    },
    askFileUpload(label='Upload a file', accept='*/*', multiple=false) {
      return _uploadUI({ label, accept, multiple: !!multiple, showPreview: false });
    },
    askAudioUpload(label='Upload audio', accept='audio/*') {
      return _uploadUI({ label, accept, showPreview: true, previewType: 'audio' });
    },
    async captureWebcam(label='Take a photo') {
      return new Promise(async (resolve, reject) => {
        let stream;
        try { stream = await navigator.mediaDevices.getUserMedia({ video: true }); }
        catch (e) { Actions.toast('Camera access denied', 'danger'); reject(e); return; }

        const wrap = document.createElement('div');
        wrap.className = 'pw-media-wrap';

        const promptEl = document.createElement('label');
        promptEl.className = 'form-label fw-semibold';
        promptEl.textContent = label;

        const vid = document.createElement('video');
        vid.autoplay = true; vid.muted = true;
        vid.className = 'w-100 rounded mb-2';
        vid.srcObject = stream;

        const captureBtn = document.createElement('button');
        captureBtn.type = 'button';
        captureBtn.className = 'btn btn-primary w-100';
        captureBtn.textContent = 'Capture';

        wrap.append(promptEl, vid, captureBtn);
        _pwCardBody().appendChild(wrap);

        captureBtn.addEventListener('click', () => {
          const canvas = document.createElement('canvas');
          canvas.width = vid.videoWidth; canvas.height = vid.videoHeight;
          canvas.getContext('2d').drawImage(vid, 0, 0);
          const url = canvas.toDataURL('image/png');
          stream.getTracks().forEach(t => t.stop());
          wrap.remove();
          resolve({ url, type: 'image/png' });
        });
      });
    },
  };
})();

// ── Room ──────────────────────────────────────────────────────────────────────
// Room.emit() broadcasts a named event to all Things in the current room.
// Room.showNav() renders Bootstrap navigation buttons for connected rooms.
// Room.take()    packages all form inputs into an inventory item (User.carry).
export const Room = {
  emit(eventName, data) {
    const room = User.location;
    Bus.emit('room:' + room + ':' + eventName, { event: eventName, data: data, room: room });
  },
  on(eventName, handler) {
    const room = User.location;
    return Bus.on('room:' + room + ':' + eventName, handler);
  },

  /**
   * Render Bootstrap navigation items for every room connected from this one.
   * Reads window._PW_NAV (injected by the page generator) — an array of
   * { id, label, call } entries, one per outgoing edge.
   *
   * Items are injected as <li class="nav-item"> into #pw-nav-list inside the
   * Bootstrap Navbar. Falls back to appending a nav card below the content
   * if the navbar list is not present.
   *
   * @param {string}  variant  Bootstrap button variant (default 'primary')
   * @param {boolean} full     Full-width buttons (default true — ignored in navbar mode)
   */
  showNav(variant = 'primary', full = true) {
    const nav = window._PW_NAV ?? [];
    if (!nav.length) return;

    // Prefer injecting into the navbar list
    const navList = document.getElementById('pw-nav-list');
    if (navList) {
      navList.innerHTML = '';
      for (const entry of nav) {
        const li  = document.createElement('li');
        li.className = 'nav-item';
        const btn = document.createElement('button');
        btn.type = 'button';
        btn.className = \`nav-link btn btn-link text-\${variant === 'primary' ? 'info' : variant} fw-semibold px-3\`;
        btn.textContent = entry.label;
        btn.addEventListener('click', () => {
          if (typeof entry.call === 'function') entry.call();
          else Navigator.goto(entry.id);
        });
        li.appendChild(btn);
        navList.appendChild(li);
      }
      return;
    }

    // Fallback: card below the content area
    const root = _pwContainer();
    let card = root.querySelector('#pw-nav-card');
    if (!card) {
      card = document.createElement('div');
      card.id = 'pw-nav-card';
      card.className = 'card mt-3';
      const body = document.createElement('div');
      body.className = 'card-body d-flex flex-column gap-2';
      card.appendChild(body);
      root.appendChild(card);
    }
    const body = card.querySelector('.card-body') ?? card;
    body.innerHTML = '';
    const btnClass = \`btn btn-\${variant} fw-semibold\${full ? ' w-100' : ''}\`;
    for (const entry of nav) {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = btnClass;
      btn.textContent = entry.label;
      btn.addEventListener('click', () => {
        if (typeof entry.call === 'function') entry.call();
        else Navigator.goto(entry.id);
      });
      body.appendChild(btn);
    }
  },

  /**
   * Package all [data-pw-input] fields in this room into a single inventory
   * item that the user carries to the next room.
   * For file/image inputs the value is read directly from Inventory (set on change).
   *
   * @param {string} into  Inventory key to carry the form data under
   */
  take(into) {
    const data = {};
    document.querySelectorAll('[data-pw-input]').forEach(el => {
      const key = el.dataset.pwInput;
      if (!key) return;
      if (el.type === 'checkbox') {
        data[key] = el.checked;
      } else if (el.type === 'file') {
        // File inputs store their value in Inventory at change-time
        data[key] = Inventory.get(key) ?? null;
      } else {
        data[key] = el.value;
        // Keep inventory in sync too
        Inventory.set(key, el.value);
      }
    });
    User.carry(into, data);
  },
};

// ── Input ─────────────────────────────────────────────────────────────────────
// 18 smart inline form inputs. Each is a standalone, self-contained program.
// Every method renders a form field directly into the page (_pwCardBody),
// sets data-pw-input="key" on the element, and establishes a two-way reactive
// bind between the DOM field and Inventory. Room.take(into) collects them all.
//
// _pwEsc / _pwEscA are local to this module for attribute/text escaping.
const _inEsc  = s => String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const _inEscA = s => String(s ?? '').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');

export const Input = {

  // ── Ask For Text ────────────────────────────────────────────────────────────
  text(key, label = '', placeholder = '', required = false, autocomplete = '', spellcheck = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="text" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control" placeholder="\${_inEscA(placeholder)}"
  \${req ? 'required aria-required="true"' : ''}
  \${autocomplete ? \`autocomplete="\${_inEscA(autocomplete)}"\` : ''}
  spellcheck="\${spellcheck ? 'true' : 'false'}"
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onInput = () => Inventory.set(key, inp.value);
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Long Text ───────────────────────────────────────────────────────
  longText(key, label = '', placeholder = '', rows = 4, required = false, spellcheck = true) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<textarea id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control" rows="\${Number(rows) || 4}" placeholder="\${_inEscA(placeholder)}"
  \${req ? 'required aria-required="true"' : ''}
  spellcheck="\${spellcheck ? 'true' : 'false'}"
  aria-describedby="\${id}-err"></textarea>
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('textarea');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onInput = () => Inventory.set(key, inp.value);
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Email Address ───────────────────────────────────────────────────
  email(key, label = '', placeholder = '', required = true) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="email" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control" placeholder="\${_inEscA(placeholder || 'you@example.com')}"
  autocomplete="email" inputmode="email" spellcheck="false"
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}">Please enter a valid email address.</div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onInput = () => Inventory.set(key, inp.value);
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Password ────────────────────────────────────────────────────────
  password(key, label = '', placeholder = '', required = true, strengthMeter = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    const showMeter = Boolean(strengthMeter) || strengthMeter === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="password" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control" placeholder="\${_inEscA(placeholder || 'Enter password')}"
  autocomplete="current-password" spellcheck="false"
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err \${showMeter ? id + '-strength' : ''}">
\${showMeter ? \`<div id="\${id}-strength" class="progress mt-1" style="height:4px" aria-hidden="true">
  <div class="progress-bar" role="progressbar" style="width:0%;transition:width .2s"></div>
</div>
<small id="\${id}-strength-label" class="text-muted"></small>\` : ''}
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onInput = () => {
      Inventory.set(key, inp.value);
      if (showMeter) {
        const v = inp.value;
        let score = 0;
        if (v.length >= 8)              score++;
        if (/[A-Z]/.test(v))           score++;
        if (/[0-9]/.test(v))           score++;
        if (/[^A-Za-z0-9]/.test(v))   score++;
        const pct = score * 25;
        const colours = ['','danger','warning','info','success'];
        const labels  = ['','Weak','Fair','Good','Strong'];
        const bar = wrap.querySelector('.progress-bar');
        const lbl = wrap.querySelector('#' + id + '-strength-label');
        if (bar) { bar.style.width = pct + '%'; bar.className = 'progress-bar' + (colours[score] ? ' bg-' + colours[score] : ''); }
        if (lbl) lbl.textContent = labels[score] ?? '';
      }
    };
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Phone Number ────────────────────────────────────────────────────
  tel(key, label = '', placeholder = '', pattern = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="tel" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control" placeholder="\${_inEscA(placeholder || '+1 (555) 000-0000')}"
  autocomplete="tel" inputmode="tel" spellcheck="false"
  \${pattern ? \`pattern="\${_inEscA(pattern)}"\` : ''}
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}">Please enter a valid phone number.</div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onInput = () => Inventory.set(key, inp.value);
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Web Address ─────────────────────────────────────────────────────
  url(key, label = '', placeholder = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="url" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control" placeholder="\${_inEscA(placeholder || 'https://example.com')}"
  autocomplete="url" inputmode="url" spellcheck="false"
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}">Please enter a valid web address.</div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onInput = () => Inventory.set(key, inp.value);
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Number ──────────────────────────────────────────────────────────
  number(key, label = '', placeholder = '', min = null, max = null, step = 1, required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="number" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control" placeholder="\${_inEscA(placeholder)}"
  inputmode="numeric"
  \${min != null ? \`min="\${Number(min)}"\` : ''}
  \${max != null ? \`max="\${Number(max)}"\` : ''}
  step="\${Number(step) || 1}"
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onInput = () => Inventory.set(key, inp.value === '' ? null : Number(inp.value));
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Numeric Range ───────────────────────────────────────────────────
  range(key, label = '', min = 0, max = 100, step = 1, showValue = true) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const showV = Boolean(showValue) || showValue === 'true';
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const initVal = Number(Inventory.get(key) ?? min);
    wrap.innerHTML = \`<label for="\${id}" class="form-label d-flex justify-content-between">
  <span>\${_inEsc(label || key)}</span>
  \${showV ? \`<span id="\${id}-val" class="badge bg-secondary">\${initVal}</span>\` : ''}
</label>
<input type="range" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-range"
  min="\${Number(min)}" max="\${Number(max)}" step="\${Number(step) || 1}"
  value="\${initVal}">\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const valDisplay = showV ? wrap.querySelector('#' + id + '-val') : null;
    const sub = Inventory.subscribe(key, v => {
      const nv = String(v ?? min);
      if (inp.value !== nv) { inp.value = nv; if (valDisplay) valDisplay.textContent = nv; }
    });
    const onInput = () => {
      Inventory.set(key, Number(inp.value));
      if (valDisplay) valDisplay.textContent = inp.value;
    };
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask For Date ────────────────────────────────────────────────────────────
  date(key, label = '', min = '', max = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="date" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control"
  \${min ? \`min="\${_inEscA(min)}"\` : ''}
  \${max ? \`max="\${_inEscA(max)}"\` : ''}
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onChange = () => Inventory.set(key, inp.value);
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => { inp.removeEventListener('change', onChange); sub.dispose(); });
  },

  // ── Ask For Date & Time ─────────────────────────────────────────────────────
  datetimeLocal(key, label = '', min = '', max = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="datetime-local" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control"
  \${min ? \`min="\${_inEscA(min)}"\` : ''}
  \${max ? \`max="\${_inEscA(max)}"\` : ''}
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onChange = () => Inventory.set(key, inp.value);
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => { inp.removeEventListener('change', onChange); sub.dispose(); });
  },

  // ── Ask For Time ────────────────────────────────────────────────────────────
  time(key, label = '', min = '', max = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="time" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control"
  \${min ? \`min="\${_inEscA(min)}"\` : ''}
  \${max ? \`max="\${_inEscA(max)}"\` : ''}
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onChange = () => Inventory.set(key, inp.value);
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => { inp.removeEventListener('change', onChange); sub.dispose(); });
  },

  // ── Ask For Month ───────────────────────────────────────────────────────────
  month(key, label = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="month" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control"
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onChange = () => Inventory.set(key, inp.value);
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => { inp.removeEventListener('change', onChange); sub.dispose(); });
  },

  // ── Ask For Week ────────────────────────────────────────────────────────────
  week(key, label = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="week" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control"
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.value = String(init);
    const sub = Inventory.subscribe(key, v => { const nv = String(v ?? ''); if (inp.value !== nv) inp.value = nv; });
    const onChange = () => Inventory.set(key, inp.value);
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => { inp.removeEventListener('change', onChange); sub.dispose(); });
  },

  // ── Ask For Color ───────────────────────────────────────────────────────────
  color(key, label = '', defaultColor = '#268bd2') {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const initVal = String(Inventory.get(key) ?? defaultColor ?? '#268bd2');
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<div class="d-flex align-items-center gap-2">
  <input type="color" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
    class="form-control form-control-color"
    value="\${_inEscA(initVal)}" title="Pick a color">
  <code id="\${id}-hex" class="text-muted small">\${_inEsc(initVal)}</code>
</div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const hexDisplay = wrap.querySelector('#' + id + '-hex');
    const sub = Inventory.subscribe(key, v => {
      const nv = String(v ?? defaultColor ?? '#268bd2');
      if (inp.value !== nv) { inp.value = nv; hexDisplay.textContent = nv; }
    });
    const onInput = () => { Inventory.set(key, inp.value); hexDisplay.textContent = inp.value; };
    inp.addEventListener('input', onInput);
    _pwRegisterBinding(() => { inp.removeEventListener('input', onInput); sub.dispose(); });
  },

  // ── Ask With Checkbox ───────────────────────────────────────────────────────
  checkbox(key, label = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3 form-check';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<input type="checkbox" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-check-input"
  \${req ? 'required' : ''}
  aria-describedby="\${id}-err">
<label class="form-check-label" for="\${id}">\${_inEsc(label || key)}</label>
<div id="\${id}-err" class="invalid-feedback d-block" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const init = Inventory.get(key);
    if (init != null) inp.checked = !!init;
    const sub = Inventory.subscribe(key, v => { if (inp.checked !== !!v) inp.checked = !!v; });
    const onChange = () => Inventory.set(key, inp.checked);
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => { inp.removeEventListener('change', onChange); sub.dispose(); });
  },

  // ── Ask With Radio Buttons ──────────────────────────────────────────────────
  radio(key, label = '', options = '', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const req = Boolean(required) || required === 'true';
    const opts = (Array.isArray(options) ? options : String(options).split(','))
      .map(o => o.trim()).filter(Boolean);
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const radios = opts.map((opt, i) => {
      const rid = id + '-' + i;
      return \`<div class="form-check">
  <input type="radio" id="\${_inEscA(rid)}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
    class="form-check-input" value="\${_inEscA(opt)}"
    \${req ? 'required' : ''}>
  <label class="form-check-label" for="\${_inEscA(rid)}">\${_inEsc(opt)}</label>
</div>\`;
    }).join('');
    wrap.innerHTML = \`<fieldset>
<legend class="form-label">\${_inEsc(label || key)}</legend>
\${radios}
<div id="\${id}-err" class="invalid-feedback d-block" data-error="\${_inEscA(key)}"></div>
</fieldset>\`;
    _pwCardBody().appendChild(wrap);
    const inputs = [...wrap.querySelectorAll('input[type="radio"]')];
    const current = Inventory.get(key);
    if (current != null) inputs.forEach(r => { r.checked = r.value === String(current); });
    const sub = Inventory.subscribe(key, v => {
      inputs.forEach(r => { r.checked = r.value === String(v ?? ''); });
    });
    const onChange = () => {
      const checked = inputs.find(r => r.checked);
      if (checked) Inventory.set(key, checked.value);
    };
    inputs.forEach(r => r.addEventListener('change', onChange));
    _pwRegisterBinding(() => { inputs.forEach(r => r.removeEventListener('change', onChange)); sub.dispose(); });
  },

  // ── Ask For File ────────────────────────────────────────────────────────────
  file(key, label = '', accept = '*/*', multiple = false, required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    const multi = Boolean(multiple) || multiple === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="file" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control"
  accept="\${_inEscA(accept || '*/*')}"
  \${multi ? 'multiple' : ''}
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-hint" class="form-text text-muted small"></div>
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const hint = wrap.querySelector('#' + id + '-hint');
    const onChange = () => {
      const files = Array.from(inp.files ?? []);
      if (!files.length) return;
      const mapped = files.map(f => ({ name: f.name, size: f.size, type: f.type, url: URL.createObjectURL(f) }));
      const val = multi ? mapped : mapped[0];
      Inventory.set(key, val);
      hint.textContent = files.map(f => f.name).join(', ');
    };
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => inp.removeEventListener('change', onChange));
  },

  // ── Ask For Image ────────────────────────────────────────────────────────────
  image(key, label = '', accept = 'image/*', required = false) {
    const id = \`pw-in-\${_inEscA(key)}\`;
    const wrap = document.createElement('div');
    wrap.className = 'mb-3';
    const req = Boolean(required) || required === 'true';
    wrap.innerHTML = \`<label for="\${id}" class="form-label">\${_inEsc(label || key)}</label>
<input type="file" id="\${id}" name="\${_inEscA(key)}" data-pw-input="\${_inEscA(key)}"
  class="form-control"
  accept="\${_inEscA(accept || 'image/*')}"
  \${req ? 'required aria-required="true"' : ''}
  aria-describedby="\${id}-err">
<div id="\${id}-preview" class="mt-2 d-none">
  <img class="img-thumbnail" style="max-height:160px;max-width:100%" alt="Preview">
</div>
<div id="\${id}-err" class="invalid-feedback" data-error="\${_inEscA(key)}"></div>\`;
    _pwCardBody().appendChild(wrap);
    const inp = wrap.querySelector('input');
    const previewWrap = wrap.querySelector('#' + id + '-preview');
    const previewImg  = previewWrap.querySelector('img');
    const onChange = () => {
      const file = inp.files?.[0];
      if (!file) return;
      const url = URL.createObjectURL(file);
      Inventory.set(key, { name: file.name, size: file.size, type: file.type, url });
      previewImg.src = url;
      previewWrap.classList.remove('d-none');
    };
    inp.addEventListener('change', onChange);
    _pwRegisterBinding(() => inp.removeEventListener('change', onChange));
  },

};

// ── Things ────────────────────────────────────────────────────────────────────
// Registry of Things inhabiting the current room.
// Things are instantiated by the page script from node.things[] definitions.
// Each registered Thing also becomes a named namespace: things.get('auth').login(...)
export const Things = (() => {
  const _reg = new Map();
  return {
    register(id, obj) {
      _reg.set(id, obj);
      registerNamespace(id, obj);
    },
    get(id)  { return _reg.get(id); },
    all()    { return [..._reg.values()]; },
    ids()    { return [..._reg.keys()]; },
    clear()  { _reg.clear(); },
  };
})();

// ── Built-in Thing classes ─────────────────────────────────────────────────────

/** WorkflowThing — a scriptable service. All behaviour is defined in event workflows.
 *  The class itself is a thin wrapper; the real logic lives in the event payload arrays. */
class WorkflowThing {
  constructor(id, config) {
    this.id     = id;
    this.config = config ?? {};
    this.name   = this.config.name ?? id;
  }
}

/** PersonaLiveThing — an AI persona that inhabits the room.
 *  Hears "message" room events and replies via any OpenAI-compatible endpoint.
 *  Works with localhost:8191 (no external server needed). */
class PersonaLiveThing {
  constructor(id, config) {
    this.id          = id;
    this.config      = config ?? {};
    this.name        = this.config.name        ?? 'Persona';
    this.personality = this.config.personality ?? '';
    this.endpoint    = this.config.endpoint    ?? 'http://localhost:8191/v1/chat/completions';
    this.model       = this.config.model       ?? 'local';
    this.replyInto   = this.config.replyInto   ?? (id + '_reply');
    this._history    = [];
  }

  async reply(userMessage) {
    this._history.push({ role: 'user', content: String(userMessage ?? '') });
    const systemPrompt = this.personality.trim()
      ? this.personality.trim()
      : ('You are ' + this.name + ', a helpful assistant.');
    try {
      const res = await fetch(this.endpoint, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model:    this.model,
          messages: [{ role: 'system', content: systemPrompt }, ...this._history],
        }),
      });
      const d     = await res.json();
      const reply = d.choices?.[0]?.message?.content ?? '(no response)';
      this._history.push({ role: 'assistant', content: reply });
      if (this.replyInto) Inventory.set(this.replyInto, reply);
      Bus.emit('thing:reply', { id: this.id, name: this.name, text: reply });
      return reply;
    } catch (e) {
      const msg = '[' + this.name + '] ' + e.message;
      Actions.toast(msg, 'danger');
      return msg;
    }
  }

  clearHistory() { this._history = []; }
}

/** AuthServerThing — wraps a real auth API. */
class AuthServerThing {
  constructor(id, config) {
    this.id        = id;
    this.config    = config ?? {};
    this.apiUrl    = this.config.apiUrl    ?? '';
    this.tokenInto = this.config.tokenInto ?? 'authToken';
  }

  async login(email, password) {
    const res  = await fetch(this.apiUrl + '/login', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    const data = await res.json();
    if (data.token) Inventory.set(this.tokenInto, data.token);
    return data;
  }

  async signup(email, password) {
    const res  = await fetch(this.apiUrl + '/signup', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    return res.json();
  }

  async validate() {
    const token = Inventory.get(this.tokenInto);
    if (!token) return false;
    try {
      const res = await fetch(this.apiUrl + '/validate', {
        headers: { 'Authorization': 'Bearer ' + token },
      });
      return res.ok;
    } catch { return false; }
  }
}

/** TestAuthServerThing — simulates auth for development. No server needed. */
class TestAuthServerThing {
  constructor(id, config) {
    this.id            = id;
    this.config        = config ?? {};
    this.tokenInto     = this.config.tokenInto     ?? 'authToken';
    this.alwaysSucceed = this.config.alwaysSucceed !== false;
  }

  async login(email, password) {
    await new Promise(r => setTimeout(r, 300)); // simulate latency
    if (this.alwaysSucceed || (email && password)) {
      const token = 'test-token-' + btoa(email).slice(0, 8);
      Inventory.set(this.tokenInto, token);
      return { ok: true, token };
    }
    return { ok: false, error: 'Invalid credentials' };
  }

  async signup(email, password) {
    await new Promise(r => setTimeout(r, 200));
    return this.alwaysSucceed ? { ok: true } : { ok: false, error: 'Signup disabled in test mode' };
  }

  async validate() {
    const token = Inventory.get(this.tokenInto);
    return !!(token && this.alwaysSucceed);
  }
}

// ── Thing registry (maps type name → class) ────────────────────────────────────
const _THING_REGISTRY = {
  WorkflowThing,
  PersonaLiveThing,
  AuthServerThing,
  TestAuthServerThing,
};

/** Factory: instantiate a Thing by type name. */
export function createThing(type, id, config) {
  const Cls = _THING_REGISTRY[type];
  if (!Cls) { console.warn('[Things] Unknown type:', type); return null; }
  return new Cls(id, config ?? {});
}

// ── Namespace registry (used by runPayload, extendable by plugins) ─────────────
// MUD metaphor: the User (player) moves through rooms (rooms), carrying
// an inventory. All aliases resolve to runtime objects — use whichever
// vocabulary felt natural in a payload step.
const _NS = {
  // Core namespaces
  Actions, actions: Actions,
  Inventory, inventory: Inventory,
  Navigator, navigator: Navigator,
  // User (Player) — the person navigating the dungeon
  User, user: User,
  Player: User, player: User,
  // DOM / form / UI shorthands
  dom:  Actions,
  form: Actions,
  ui:   Actions,
  // Display — write content into existing elements
  Display, display: Display,
  // Render — build page components at runtime (use with template: "blank")
  Render, render: Render,
  // Media — file/camera upload UI
  Media, media: Media,
  // Room — emit events, show navigation, take forms
  Room, room: Room,
  // Things — registry of Thing instances inhabiting the current room
  Things, things: Things,
  // Input — 18 smart reactive form inputs (two-way bound to Inventory)
  Input, input: Input,
  // "http" maps to Actions (which contains .get, .post, .fetch)
  http: Actions,
};

/** Register a plugin namespace so runPayload can resolve it. */
export function registerNamespace(name, obj) {
  _NS[name] = obj;
  _NS[name.toLowerCase()] = obj;
}

// ── Diamond Router ────────────────────────────────────────────────────────────
export function route(routes) {
  const inv = Inventory.dump();
  for (const { condition, target } of routes) {
    try {
      if (!condition || condition === 'true' ||
          (new Function('inventory', 'return !!(' + condition + ')')(inv))) {
        History.push(target);
        Navigator.goto(target);
        return;
      }
    } catch (e) { console.warn('[route] condition error:', condition, e); }
  }
  // No route matched — surface the error so it doesn't silently hang
  console.warn('[route] no condition matched — inventory:', inv);
  Bus.emit('route:noMatch', { routes, inventory: inv });
  Actions.toast('Navigation error: no path matched. Please go back.', 'warning');
}

// ── Payload Runner ────────────────────────────────────────────────────────────
// Supports:
//   action: "Namespace.method"  OR  "namespace.method"  OR  "method"
//   params: { arg1, arg2, ..., into: "inventoryKey" }
//
// If the action returns a value and "into" is specified, the value is stored
// in Inventory under that key.
export async function runPayload(steps) {
  for (const step of (steps ?? [])) {
    try {
      const { action, params = {} } = step;
      const dot  = action.indexOf('.');
      const ns   = dot >= 0 ? action.slice(0, dot) : 'Actions';
      const fn   = dot >= 0 ? action.slice(dot + 1) : action;

      const target = _NS[ns];

      // Extract "into" before building fn args (it's a meta-param, not passed to the fn)
      const { into, ...rest } = params;
      const fnArgs = Object.values(rest);

      let result;
      if (target?.[fn]) {
        result = await target[fn](...fnArgs);
      } else {
        console.warn('[runPayload] unknown action:', action, '— known namespaces:', Object.keys(_NS).filter(k => k[0] === k[0].toUpperCase()));
      }

      // Store return value in inventory if "into" was specified
      if (into !== undefined && result !== undefined) {
        Inventory.set(into, result);
      }
    } catch (e) { console.error('[payload]', step, e); }
  }
}
${extCode}`;
}
